// components/designsData.js

export const designs = [
  {
    id: 1,
    title: "ID NO : 01",
    category: "Madrasa",
    thumbnail: "/idCard/001.jpeg",
    fullImage: "/idCard/001.jpeg",
  },
  {
    id: 2,
    title: "ID NO : 02",
    category: "Madrasa",
    thumbnail: "/idCard/002.jpeg",
    fullImage: "/idCard/002.jpeg",
  },
  {
    id: 3,
    title: "ID NO : 03",
    category: "Madrasa",
    thumbnail: "/idCard/003.jpeg",
    fullImage: "/idCard/003.jpeg",
  },
  {
    id: 4,
    title: "ID NO : 04",
    category: "Madrasa",
    thumbnail: "/idCard/004.jpeg",
    fullImage: "/idCard/004.jpeg",
  },
  {
    id: 5,
    title: "ID NO : 05",
    category: "Madrasa",
    thumbnail: "/idCard/005.jpeg",
    fullImage: "/idCard/005.jpeg",
  },
  {
    id: 6,
    title: "ID NO : 06",
    category: "Madrasa",
    thumbnail: "/idCard/006.jpeg",
    fullImage: "/idCard/006.jpeg",
  },
  {
    id: 7,
    title: "ID NO : 07",
    category: "Madrasa",
    thumbnail: "/idCard/007.jpeg",
    fullImage: "/idCard/007.jpeg",
  },
  {
    id: 8,
    title: "ID NO : 08",
    category: "Madrasa",
    thumbnail: "/idCard/008.jpeg",
    fullImage: "/idCard/008.jpeg",
  },
  {
    id: 9,
    title: "ID NO : 09",
    category: "Madrasa",
    thumbnail: "/idCard/009.jpeg",
    fullImage: "/idCard/009.jpeg",
  },
  {
    id: 10,
    title: "ID NO : 010",
    category: "Madrasa",
    thumbnail: "/idCard/010.jpeg",
    fullImage: "/idCard/010.jpeg",
  },
  {
    id: 11,
    title: "ID NO : 11",
    category: "Madrasa",
    thumbnail: "/idCard/011.jpeg",
    fullImage: "/idCard/011.jpeg",
  },
  {
    id: 12,
    title: "ID NO : 12",
    category: "Madrasa",
    thumbnail: "/idCard/012.jpeg",
    fullImage: "/idCard/012.jpeg",
  },
  {
    id: 13,
    title: "ID NO : 13",
    category: "Office",
    thumbnail: "/idCard/013.jpeg",
    fullImage: "/idCard/013.jpeg",
  },
  {
    id: 14,
    title: "ID NO : 14",
    category: "School",
    thumbnail: "/idCard/014.jpeg",
    fullImage: "/idCard/014.jpeg",
  },
  {
    id: 15,
    title: "ID NO : 15",
    category: "Madrasa",
    thumbnail: "/idCard/015.jpeg",
    fullImage: "/idCard/015.jpeg",
  },
  {
    id: 16,
    title: "ID NO : 16",
    category: "Madrasa",
    thumbnail: "/idCard/016.jpeg",
    fullImage: "/idCard/016.jpeg",
  },
  {
    id: 17,
    title: "ID NO : 17",
    category: "Madrasa",
    thumbnail: "/idCard/017.jpeg",
    fullImage: "/idCard/017.jpeg",
  },
  {
    id: 18,
    title: "ID NO : 18",
    category: "Office",
    thumbnail: "/idCard/018.jpeg",
    fullImage: "/idCard/018.jpeg",
  },
  {
    id: 19,
    title: "ID NO : 19",
    category: "Madrasa",
    thumbnail: "/idCard/019.jpeg",
    fullImage: "/idCard/019.jpeg",
  },
  {
    id: 20,
    title: "ID NO : 20",
    category: "Office",
    thumbnail: "/idCard/020.jpeg",
    fullImage: "/idCard/020.jpeg",
  },
  {
    id: 21,
    title: "ID NO : 21",
    category: "Office",
    thumbnail: "/idCard/021.jpeg",
    fullImage: "/idCard/021.jpeg",
  },
  {
    id: 22,
    title: "ID NO : 22",
    category: "School",
    thumbnail: "/idCard/022.jpeg",
    fullImage: "/idCard/022.jpeg",
  },
  {
    id: 23,
    title: "ID NO : 23",
    category: "Madrasa",
    thumbnail: "/idCard/023.jpeg",
    fullImage: "/idCard/023.jpeg",
  },
  {
    id: 24,
    title: "ID NO : 24",
    category: "Madrasa",
    thumbnail: "/idCard/024.jpeg",
    fullImage: "/idCard/024.jpeg",
  },
  {
    id: 25,
    title: "ID NO : 25",
    category: "School",
    thumbnail: "/idCard/025.png",
    fullImage: "/idCard/025.png",
  },
  {
    id: 26,
    title: "ID NO : 26",
    category: "Madrasa",
    thumbnail: "/idCard/026.png",
    fullImage: "/idCard/026.png",
  },
  {
    id: 27,
    title: "ID NO : 27",
    category: "School",
    thumbnail: "/idCard/027.png",
    fullImage: "/idCard/027.png",
  },
  {
    id: 28,
    title: "ID NO : 28",
    category: "Madrasa",
    thumbnail: "/idCard/028.png",
    fullImage: "/idCard/028.png",
  },
  {
    id: 29,
    title: "ID NO : 29",
    category: "Madrasa",
    thumbnail: "/idCard/029.png",
    fullImage: "/idCard/029.png",
  },
  {
    id: 30,
    title: "ID NO : 30",
    category: "Office",
    thumbnail: "/idCard/030.jpeg",
    fullImage: "/idCard/030.jpeg",
  },
  {
    id: 31,
    title: "ID NO : 31",
    category: "School",
    thumbnail: "/idCard/031.jpeg",
    fullImage: "/idCard/031.jpeg",
  },
  {
    id: 32,
    title: "ID NO : 32",
    category: "Madrasa",
    thumbnail: "/idCard/032.jpeg",
    fullImage: "/idCard/032.jpeg",
  },
  {
    id: 33,
    title: "ID NO : 33",
    category: "Madrasa",
    thumbnail: "/idCard/033.jpeg",
    fullImage: "/idCard/033.jpeg",
  },
  {
    id: 34,
    title: "ID NO : 34",
    category: "Madrasa",
    thumbnail: "/idCard/034.jpeg",
    fullImage: "/idCard/034.jpeg",
  },
  {
    id: 35,
    title: "ID NO : 35",
    category: "Madrasa",
    thumbnail: "/idCard/035.jpeg",
    fullImage: "/idCard/035.jpeg",
  },
  {
    id: 36,
    title: "ID NO : 36",
    category: "Madrasa",
    thumbnail: "/idCard/036.jpeg",
    fullImage: "/idCard/036.jpeg",
  },
  {
    id: 37,
    title: "ID NO : 37",
    category: "Madrasa",
    thumbnail: "/idCard/037.jpeg",
    fullImage: "/idCard/037.jpeg",
  },
  {
    id: 38,
    title: "ID NO : 38",
    category: "Madrasa",
    thumbnail: "/idCard/038.jpeg",
    fullImage: "/idCard/038.jpeg",
  },
  {
    id: 39,
    title: "ID NO : 39",
    category: "Madrasa",
    thumbnail: "/idCard/039.jpeg",
    fullImage: "/idCard/039.jpeg",
  },
  {
    id: 40,
    title: "ID NO : 40",
    category: "Madrasa",
    thumbnail: "/idCard/040.jpeg",
    fullImage: "/idCard/040.jpeg",
  },
  {
    id: 41,
    title: "ID NO : 41",
    category: "Madrasa",
    thumbnail: "/idCard/041.jpeg",
    fullImage: "/idCard/041.jpeg",
  },
  {
    id: 42,
    title: "ID NO : 42",
    category: "Madrasa",
    thumbnail: "/idCard/042.jpeg",
    fullImage: "/idCard/042.jpeg",
  },
  {
    id: 43,
    title: "ID NO : 43",
    category: "School",
    thumbnail: "/idCard/043.jpeg",
    fullImage: "/idCard/043.jpeg",
  },
  {
    id: 44,
    title: "ID NO : 44",
    category: "School",
    thumbnail: "/idCard/044.jpeg",
    fullImage: "/idCard/044.jpeg",
  },
  {
    id: 45,
    title: "ID NO : 45",
    category: "School",
    thumbnail: "/idCard/045.jpeg",
    fullImage: "/idCard/045.jpeg",
  },
  {
    id: 46,
    title: "ID NO : 46",
    category: "School",
    thumbnail: "/idCard/046.jpeg",
    fullImage: "/idCard/046.jpeg",
  },
  {
    id: 47,
    title: "ID NO : 47",
    category: "School",
    thumbnail: "/idCard/047.jpeg",
    fullImage: "/idCard/047.jpeg",
  },
  {
    id: 48,
    title: "ID NO : 48",
    category: "School",
    thumbnail: "/idCard/048.jpeg",
    fullImage: "/idCard/048.jpeg",
  },
  {
    id: 49,
    title: "ID NO : 49",
    category: "School",
    thumbnail: "/idCard/049.jpeg",
    fullImage: "/idCard/049.jpeg",
  },
  {
    id: 50,
    title: "ID NO : 50",
    category: "Office",
    thumbnail: "/idCard/050.jpeg",
    fullImage: "/idCard/050.jpeg",
  },
  {
    id: 51,
    title: "ID NO : 51",
    category: "School",
    thumbnail: "/idCard/051.jpeg",
    fullImage: "/idCard/051.jpeg",
  },
  {
    id: 52,
    title: "ID NO : 52",
    category: "School",
    thumbnail: "/idCard/052.jpeg",
    fullImage: "/idCard/052.jpeg",
  },
  {
    id: 53,
    title: "ID NO : 53",
    category: "School",
    thumbnail: "/idCard/053.jpeg",
    fullImage: "/idCard/053.jpeg",
  },
  {
    id: 54,
    title: "ID NO : 54",
    category: "School",
    thumbnail: "/idCard/054.jpeg",
    fullImage: "/idCard/054.jpeg",
  },
  {
    id: 55,
    title: "ID NO : 55",
    category: "School",
    thumbnail: "/idCard/055.jpeg",
    fullImage: "/idCard/055.jpeg",
  },
  {
    id: 56,
    title: "ID NO : 56",
    category: "School",
    thumbnail: "/idCard/056.jpeg",
    fullImage: "/idCard/056.jpeg",
  },
  {
    id: 57,
    title: "ID NO : 57",
    category: "School",
    thumbnail: "/idCard/057.jpeg",
    fullImage: "/idCard/057.jpeg",
  },
  {
    id: 58,
    title: "ID NO : 58",
    category: "School",
    thumbnail: "/idCard/058.jpeg",
    fullImage: "/idCard/058.jpeg",
  },
  {
    id: 59,
    title: "ID NO : 59",
    category: "Office",
    thumbnail: "/idCard/059.jpeg",
    fullImage: "/idCard/059.jpeg",
  },
  {
    id: 60,
    title: "ID NO : 60",
    category: "Madrasa",
    thumbnail: "/idCard/060.jpeg",
    fullImage: "/idCard/060.jpeg",
  },
  {
    id: 61,
    title: "ID NO : 61",
    category: "School",
    thumbnail: "/idCard/061.jpeg",
    fullImage: "/idCard/061.jpeg",
  },
  {
    id: 62,
    title: "ID NO : 62",
    category: "Madrasa",
    thumbnail: "/idCard/062.jpeg",
    fullImage: "/idCard/062.jpeg",
  },
  {
    id: 63,
    title: "ID NO : 63",
    category: "School",
    thumbnail: "/idCard/063.jpeg",
    fullImage: "/idCard/063.jpeg",
  },
  {
    id: 64,
    title: "ID NO : 64",
    category: "School",
    thumbnail: "/idCard/064.jpeg",
    fullImage: "/idCard/064.jpeg",
  },
  {
    id: 65,
    title: "ID NO : 65",
    category: "Office",
    thumbnail: "/idCard/065.jpeg",
    fullImage: "/idCard/065.jpeg",
  },
  {
    id: 66,
    title: "ID NO : 66",
    category: "School",
    thumbnail: "/idCard/066.jpeg",
    fullImage: "/idCard/066.jpeg",
  },
  {
    id: 67,
    title: "ID NO : 67",
    category: "School",
    thumbnail: "/idCard/067.jpeg",
    fullImage: "/idCard/067.jpeg",
  },
  {
    id: 68,
    title: "ID NO : 68",
    category: "School",
    thumbnail: "/idCard/068.jpeg",
    fullImage: "/idCard/068.jpeg",
  },
  {
    id: 69,
    title: "ID NO : 69",
    category: "School",
    thumbnail: "/idCard/069.jpeg",
    fullImage: "/idCard/069.jpeg",
  },
  {
    id: 70,
    title: "ID NO : 70",
    category: "School",
    thumbnail: "/idCard/070.jpeg",
    fullImage: "/idCard/070.jpeg",
  },
  {
    id: 71,
    title: "ID NO : 71",
    category: "Office",
    thumbnail: "/idCard/071.jpeg",
    fullImage: "/idCard/071.jpeg",
  },
  {
    id: 72,
    title: "ID NO : 72",
    category: "School",
    thumbnail: "/idCard/072.jpeg",
    fullImage: "/idCard/072.jpeg",
  },
  {
    id: 73,
    title: "ID NO : 73",
    category: "School",
    thumbnail: "/idCard/073.jpeg",
    fullImage: "/idCard/073.jpeg",
  },
  {
    id: 74,
    title: "ID NO : 74",
    category: "Madrasa",
    thumbnail: "/idCard/074.jpeg",
    fullImage: "/idCard/074.jpeg",
  },
  {
    id: 75,
    title: "ID NO : 75",
    category: "Madrasa",
    thumbnail: "/idCard/075.jpeg",
    fullImage: "/idCard/075.jpeg",
  },
  {
    id: 76,
    title: "ID NO : 76",
    category: "School",
    thumbnail: "/idCard/076.jpeg",
    fullImage: "/idCard/076.jpeg",
  },
  {
    id: 77,
    title: "ID NO : 77",
    category: "Madrasa",
    thumbnail: "/idCard/077.jpeg",
    fullImage: "/idCard/077.jpeg",
  },
  {
    id: 78,
    title: "ID NO : 78",
    category: "School",
    thumbnail: "/idCard/078.jpeg",
    fullImage: "/idCard/078.jpeg",
  },
  {
    id: 79,
    title: "ID NO : 79",
    category: "Madrasa",
    thumbnail: "/idCard/079.jpeg",
    fullImage: "/idCard/079.jpeg",
  },
  {
    id: 80,
    title: "ID NO : 80",
    category: "Madrasa",
    thumbnail: "/idCard/080.jpeg",
    fullImage: "/idCard/080.jpeg",
  },
  {
    id: 81,
    title: "ID NO : 81",
    category: "School",
    thumbnail: "/idCard/081.jpeg",
    fullImage: "/idCard/081.jpeg",
  },
  {
    id: 82,
    title: "ID NO : 82",
    category: "Madrasa",
    thumbnail: "/idCard/082.jpeg",
    fullImage: "/idCard/082.jpeg",
  },
  {
    id: 83,
    title: "ID NO : 83",
    category: "Madrasa",
    thumbnail: "/idCard/083.jpeg",
    fullImage: "/idCard/083.jpeg",
  },
  {
    id: 84,
    title: "ID NO : 84",
    category: "Madrasa",
    thumbnail: "/idCard/084.jpeg",
    fullImage: "/idCard/084.jpeg",
  },
  {
    id: 85,
    title: "ID NO : 85",
    category: "Madrasa",
    thumbnail: "/idCard/085.jpeg",
    fullImage: "/idCard/085.jpeg",
  },
  {
    id: 86,
    title: "ID NO : 86",
    category: "Madrasa",
    thumbnail: "/idCard/086.jpeg",
    fullImage: "/idCard/086.jpeg",
  },
  {
    id: 87,
    title: "ID NO : 87",
    category: "Madrasa",
    thumbnail: "/idCard/087.jpeg",
    fullImage: "/idCard/087.jpeg",
  },
];
