// components/designsData.js

export const designs = [
  {
    id: 1,
    title: "ID NO : 01",
    category: "Madrasa",
    thumbnail: "/id01.jpeg",
    fullImage: "/id03.jpeg",
  },
  {
    id: 2,
    title: "ID NO : 02",
    category: "School",
    thumbnail: "/id02.jpeg",
    fullImage: "/id03.jpeg",
  },
  {
    id: 3,
    title: "ID NO : 03",
    category: "Office",
    thumbnail: "/id03.jpeg",
    fullImage: "/id01.jpeg",
  },
  {
    id: 4,
    title: "ID NO : 04",
    category: "Madrasa",
    thumbnail: "/id01.jpeg",
    fullImage: "/id03.jpeg",
  },
  {
    id: 5,
    title: "ID NO : 05",
    category: "School",
    thumbnail: "/id02.jpeg",
    fullImage: "/id03.jpeg",
  },
  {
    id: 6,
    title: "ID NO : 06",
    category: "Office",
    thumbnail: "/id03.jpeg",
    fullImage: "/id01.jpeg",
  },
  {
    id: 7,
    title: "ID NO : 07",
    category: "Madrasa",
    thumbnail: "/id01.jpeg",
    fullImage: "/id03.jpeg",
  },
  {
    id: 8,
    title: "ID NO : 08",
    category: "School",
    thumbnail: "/id02.jpeg",
    fullImage: "/id03.jpeg",
  },
  {
    id: 9,
    title: "ID NO : 09",
    category: "Office",
    thumbnail: "/id03.jpeg",
    fullImage: "/id01.jpeg",
  },
  {
    id: 10,
    title: "ID NO : 010",
    category: "Madrasa",
    thumbnail: "/id01.jpeg",
    fullImage: "/id03.jpeg",
  },
  {
    id: 11,
    title: "ID NO : 11",
    category: "School",
    thumbnail: "/id02.jpeg",
    fullImage: "/id03.jpeg",
  },
  {
    id: 12,
    title: "ID NO : 12",
    category: "Office",
    thumbnail: "/id03.jpeg",
    fullImage: "/id01.jpeg",
  },
  {
    id: 13,
    title: "ID NO : 13",
    category: "Madrasa",
    thumbnail: "/id01.jpeg",
    fullImage: "/id03.jpeg",
  },
  {
    id: 14,
    title: "ID NO : 14",
    category: "School",
    thumbnail: "/id02.jpeg",
    fullImage: "/id03.jpeg",
  },
  {
    id: 15,
    title: "ID NO : 15",
    category: "Office",
    thumbnail: "/id03.jpeg",
    fullImage: "/id01.jpeg",
  },
  {
    id: 16,
    title: "ID NO : 16",
    category: "Madrasa",
    thumbnail: "/id01.jpeg",
    fullImage: "/id03.jpeg",
  },
  {
    id: 17,
    title: "ID NO : 17",
    category: "School",
    thumbnail: "/id02.jpeg",
    fullImage: "/id03.jpeg",
  },
  {
    id: 18,
    title: "ID NO : 18",
    category: "Office",
    thumbnail: "/id03.jpeg",
    fullImage: "/id01.jpeg",
  },

  // আরও ডামি ডেটা যোগ করা যাবে
];
